### ISSUE TITLE
SCD for Place Recognition

### ISSUE THREAD

**Issue by h-rover** [gisbi-kim/FAST_LIO_SLAM#1]
Hi,

First of all, great work and packages. Do you plan on integrating the release of SCD for place recognition ? Like the way they are generated in SC-LIO-SAM. Also, are you planning on releasing the place recognition cpp based implemented package(ROS) anytime soon for quick tests? Thanks.

**Comment by gisbi-kim** [comment]
@h-rover  
The SCD saver as in SC-LIO-SAM will be supported soon (by July). then, I'll update the readme.

also, currently Scan Context Manager is integrated with ROS, please see the https://github.com/gisbi-kim/FAST_LIO_SLAM/blob/main/SC-PGO/src/laserPosegraphOptimization.cpp.

If you need a more quick test, please use our matlab or python-based implementations 
- matlab: https://github.com/irapkaist/scancontext/tree/master/fast_evaluator
- python: https://github.com/gisbi-kim/PyICP-SLAM

thank you.

**Comment by gisbi-kim** [comment]
@h-rover  one thing to add;
I guess LT-SLAM might be the one you want to find.
https://github.com/gisbi-kim/lt-mapper

it uses SCDs for long-term localization and align two given trajectories

**Comment by MigVega** [comment]
I am afraid this capabilities (to generate the set of session data) are still not implemented in FAST_LIO_SLAM, am I right?

**Comment by MigVega** [comment]
Ok, now it has/ will have after this pull request get accepted: https://github.com/gisbi-kim/FAST_LIO_SLAM/pull/34 #34
