### ISSUE TITLE
How to tune parameters for indoor environment?

### ISSUE THREAD

**Issue by yanliang-wang** [gisbi-kim/FAST_LIO_SLAM#13]
Hello, @gisbi-kim  this work is very cool.

But it does not work well in my indoor test. My sensors are Velodyne16 and Xsens Mti-300. I adjust some parameters(reduce `sc_dist_thres` to `0.2`, reduce `sc_max_radius` to `20`) , but it still does not work.
![image](https://user-images.githubusercontent.com/35984711/129823227-e3f21c6f-f8ed-4aef-837d-db59ca54490f.png)

Can you give me some advice about how to tune parameters in my indoor test? I'll appreciate it. Thanks in advance!

**Comment by gisbi-kim** [comment]
Hi, @yanliang-wang 
thanks for using our project. 
I think the parameter is good for the indoor env. 

but the current version of SC-PGO in this repository does not support the reverse-loop-closing. 
(Actually Scan Context supports reverse loop detections, but only for when 360 deg horizontal fov is available. In common cases, a robot loses it rear or some horizontal fovs so I just ommited the reverse loop closings using scan context) 

For the reverse loop detections and closings, I've been using radius-search-based search. 
the radius-search-based loop closing was not implemented in this SC-PGO yet, but in SC-LIO-SAM or SC-LeGO-LOAM - please use them.

**Comment by yanliang-wang** [comment]
Thanks, that makes much sense. I'll have a try. Thank you for this work again.

**Comment by yanliang-wang** [comment]
Hi, @gisbi-kim. Thanks for your reply again. That helped a lot. I tried radius-search-based loop closure detection and that worked very well for reverse-loop-closing. 

By the way, scan context is also a nice work. Thanks for your share.

**Comment by yanliang-wang** [comment]
Hi, @gisbi-kim @marshal-shi , I released my implementation of the radius-search-based loop closure in [the repository,](https://github.com/yanliang-wang/FAST_LIO_LC) in which the pose and map in the iterated extended Kalman filter of FAST-LIO will be updated according to the pose graph optimization. This is different from the implementation of FAST_LIO_SLAM and I think this will improve its performance.

You can have a try if you are interested in it.

**Comment by marshal-shi** [comment]
@yanliang-wang well done. Just checked the video. The result looks promising. Will check code later. 
Well done.

**Comment by yanliang-wang** [comment]
> @yanliang-wang cool!!! thanks! I'll link your repo within the readme.

Wow, it's my pleasure. Thanks for your interest in it.
