### ISSUE TITLE
Error transforming odometry 'pgoOdom' from frame '/camera_init' to frame 'camera_init'

### ISSUE THREAD

**Issue by Auto-RunningWang** [gisbi-kim/FAST_LIO_SLAM#15]
Hello @gisbi-kim , thank you for your amazing work. I tried FAST_LIO_SLAM(using KAIST 03 sequence of MulRan dataset).I got transforming error when I launched "aloam_velodyne fastlio_ouster64.launch" and then crashed, just the following result.Pelase give me some advice for the error,thanks!
![Screenshot from 2021-09-01 21-09-32](https://user-images.githubusercontent.com/42669562/131677093-df4bc956-a29b-4bc4-bafb-4c712404d2e3.png)

**Comment by harveybia** [comment]
Refer to: https://github.com/laboshinl/loam_velodyne/issues/157
Changing all the `/camera_init` frames to `camera_init` in the code fixed this for me.

**Comment by ManChrys** [comment]
Hello @Auto-RunningWang 

Did you try to remove all gtsam versions and install everything from the beginning, following the steps on issue #8 ?

**Comment by Auto-RunningWang** [comment]
> Refer to: [laboshinl/loam_velodyne#157](https://github.com/laboshinl/loam_velodyne/issues/157)
> Changing all the `/camera_init` frames to `camera_init` in the code fixed this for me.

Hello my friend. Thanks for your answer. I tried this change but it did not work in the right way, and i got the new warning message "Invalid argument "/camera_init" passed to canTransform argument target_frame in tf2 frame_ids cannot start with a '/' like:". Is there any other case I should care about?

**Comment by Auto-RunningWang** [comment]
Hello @ManChrys, I installed gtsam 4.0.3 and this bug looks like related to coordinate frame. Are you sure change gtsam version can make difference?

**Comment by Auto-RunningWang** [comment]
> Hello @ManChrys, I installed gtsam 4.0.3 and this bug looks like related to coordinate frame. Are you sure change gtsam version can make difference?

@ManChrys Thank you very much. I tried your advice to reinstall gtsam following the guidance of issue #8 and solved the program crash bug.

**Comment by Auto-RunningWang** [comment]
At last, I solved my problem based on the advice of @harveybia and @ManChrys

**Comment by ManChrys** [comment]
Yeah all these pgo errors have to do with gtsam version. That's my opinion. I'm happy that my answer helps you my friend. Have a nice day!!
