### ISSUE TITLE
how to set lidar type when i use livox horiz

### ISSUE THREAD

**Issue by Lenotary** [gisbi-kim/FAST_LIO_SLAM#2]
how to set lidar type when i use livox horizon

**Comment by kxch928925819** [comment]
rviz
PGO MAP
topic 
/cloud_registered
you will see the pointcloud!

**Comment by gisbi-kim** [comment]
@kxch928925819 thank you for helping me!

@Lenotary  I hope the above comment works. 
I close this issue.
