### ISSUE TITLE
Build error with EIGEN

### ISSUE THREAD

**Issue by infinitysky** [gisbi-kim/FAST_LIO_SLAM#23]
```
  from /home/ubuntu/slam_test/ws_livox/src/FAST_LIO_SLAM/SC-PGO/src/laserMapping.cpp:53:
/usr/local/include/eigen3/Eigen/src/Eigenvalues/Tridiagonalization.h:550:5: error: ‘EIGEN_CONSTEXPR’ does not name a type; did you mean ‘EIGEN_HAS_CONSTEXPR’?
  550 |     EIGEN_CONSTEXPR Index rows() const EIGEN_NOEXCEPT { return m_matrix.rows(); }
      |     ^~~~~~~~~~~~~~~ 
```
Hi sir
I am trying to rebuild this project with the following environment 
Ubuntu 20.04 TLS
ROS Noetic 
Eigen 3.4.0

I can build and run the current FAST_LIO, but when I start include your project, it will show me a loooong list of error message. mainly about Eigen 

Could you help me to check the version of the Eigen ?

**Comment by infinitysky** [comment]
I think iresolved this issue. This issues caused by the library v3.4, after I installed a older version v.3.3.x problem resolved

**Comment by mayuxiang1995** [comment]
I change the #include <eigen3/Eigen/Dense> to #include <Eigen/Eigen> to solve this problem
