### ISSUE TITLE
The PGO loops forever

### ISSUE THREAD

**Issue by JzHuai0108** [gisbi-kim/FAST_LIO_SLAM#28]
Thank you for the great work.
In running fastlio_slam, one inconvenience I have experienced is that the SC_PGO loops for ever long after the rosbag have completed.
Do you have some suggestion on how to terminate the PGO loop besides using Ctrl+C in the terminal?

Thanks,

**Comment by qlibp** [comment]
SC_PGO should loop, but it may not need to keep invoking `runISAM2opt()`. Just add one more conditional flag to skip this.

**Comment by JzHuai0108** [comment]
Thank you for the reply. So I did.
