### ISSUE TITLE
livox-horizon

### ISSUE THREAD

**Issue by kxch928925819** [gisbi-kim/FAST_LIO_SLAM#3]

**Comment by Lenotary** [comment]
thank for you reply ☺

**Comment by kxch928925819** [comment]
# terminal 1: 
dji@dji-MANIFOLD-2-C:~/catkin_fastlio_slam$ roslaunch aloam_velodyne fastlio_ouster64.launch 
... logging to /home/dji/.ros/log/89e264e8-ec53-11eb-91ef-34d26269e60d/roslaunch-dji-MANIFOLD-2-C-27957.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dji-MANIFOLD-2-C:43321/

SUMMARY
========

PARAMETERS
 * /keyframe_meter_gap: 0.5
 * /lidar_type: OS1-64
 * /mapping_line_resolution: 0.4
 * /mapping_plane_resolution: 0.8
 * /mapviz_filter_size: 0.05
 * /minimum_range: 0.5
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /save_directory: /home/user/Deskto...
 * /sc_dist_thres: 0.3
 * /sc_max_radius: 80.0
 * /scan_line: 64

NODES
  /
    alaserPGO (aloam_velodyne/alaserPGO)
    rvizscpgo (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[alaserPGO-1]: started with pid [27979]
process[rvizscpgo-2]: started with pid [27980]
rm: cannot remove '/home/user/Desktop/catkin_fastlio_slam/data/Scans/': No such file or directory
mkdir: cannot create directory ‘/home/user/Desktop’: Permission denied
posegraph prior node 0 added
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Error during open!
[alaserPGO-1] process has died [pid 27979, exit code -6, cmd /home/dji/catkin_fastlio_slam/devel/lib/aloam_velodyne/alaserPGO /aft_mapped_to_init:=/Odometry /velodyne_cloud_registered_local:=/cloud_registered_body /cloud_for_scancontext:=/cloud_registered_lidar __name:=alaserPGO __log:=/home/dji/.ros/log/89e264e8-ec53-11eb-91ef-34d26269e60d/alaserPGO-1.log].
log file: /home/dji/.ros/log/89e264e8-ec53-11eb-91ef-34d26269e60d/alaserPGO-1*.log


    # open the other terminal tab: 
    dji@dji-MANIFOLD-2-C:~/catkin_fastlio_slam$ roslaunch fast_lio mapping_horizon.launch
... logging to /home/dji/.ros/log/89e264e8-ec53-11eb-91ef-34d26269e60d/roslaunch-dji-MANIFOLD-2-C-27670.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dji-MANIFOLD-2-C:40919/

SUMMARY
========

PARAMETERS
 * /common/imu_topic: /livox/imu
 * /common/lid_topic: /livox/lidar
 * /common/time_sync_en: False
 * /cube_side_length: 1000.0
 * /dense_publish_enable: True
 * /feature_extract_enable: False
 * /filter_size_map: 0.5
 * /filter_size_surf: 0.5
 * /mapping/acc_cov: 0.1
 * /mapping/b_acc_cov: 0.0001
 * /mapping/b_gyr_cov: 0.0001
 * /mapping/det_range: 260.0
 * /mapping/extrinsic_R: [1, 0, 0, 0, 1, 0...
 * /mapping/extrinsic_T: [0.05512, 0.02226...
 * /mapping/fov_degree: 100
 * /mapping/gyr_cov: 0.1
 * /max_iteration: 3
 * /pcd_save_enable: False
 * /point_filter_num: 3
 * /preprocess/blind: 4
 * /preprocess/lidar_type: 1
 * /preprocess/scan_line: 6
 * /publish/dense_publish_en: ture
 * /publish/scan_bodyframe_pub_en: True
 * /publish/scan_publish_en: True
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /runtime_pos_log_enable: False
 * /scan_publish_enable: True

NODES
  /
    laserMapping (fast_lio/fastlio_mapping)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [27687]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 89e264e8-ec53-11eb-91ef-34d26269e60d
process[rosout-1]: started with pid [27705]
started core service [/rosout]
process[laserMapping-2]: started with pid [27708]
process[rviz-3]: started with pid [27713]
Multi thread started 
p_pre->lidar_type 1
~~~~/home/dji/catkin_fastlio_slam/src/FAST_LIO_SLAM/FAST-LIO/ file opened
IMU and LiDAR not Synced, IMU time: 1024.697791, lidar scan end time: 0.000000[ INFO] [1627113064.622261038]: IMU Initial Done

**Comment by kxch928925819** [comment]
haha! I,m fool!
<param name="save_directory" type="string" value="/home/user/Desktop/catkin_fastlio_slam/data/"/>

**Comment by kxch928925819** [comment]
[ 62%] Built target fast_lio_generate_messages_eus
[ 64%] Built target fast_lio_generate_messages_lisp
[ 64%] Built target livox_ros_driver_generate_messages
[ 66%] Built target fast_lio_generate_messages_nodejs
[ 66%] Built target fast_lio_generate_messages
[ 95%] Built target livox_ros_driver_node
/home/dji/catkin_fastlio_slam/src/FAST_LIO_SLAM/SC-PGO/src/laserPosegraphOptimization.cpp: In function ‘int main(int, char**)’:
/home/dji/catkin_fastlio_slam/src/FAST_LIO_SLAM/SC-PGO/src/laserPosegraphOptimization.cpp:781:10: warning: variable ‘unused’ set but not used [-Wunused-but-set-variable]
     auto unused = system((std::string("exec rm -r ") + pgScansDirectory).c_str());
          ^~~~~~
[ 97%] Linking CXX executable /home/dji/catkin_fastlio_slam/devel/lib/aloam_velodyne/alaserPGO
/usr/bin/ld: CMakeFiles/alaserPGO.dir/src/laserPosegraphOptimization.cpp.o: undefined reference to symbol '_ZN3tbb8internal23allocate_via_handler_v3Em'
//usr/lib/x86_64-linux-gnu/libtbb.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
FAST_LIO_SLAM/SC-PGO/CMakeFiles/alaserPGO.dir/build.make:402: recipe for target '/home/dji/catkin_fastlio_slam/devel/lib/aloam_velodyne/alaserPGO' failed
make[2]: *** [/home/dji/catkin_fastlio_slam/devel/lib/aloam_velodyne/alaserPGO] Error 1
CMakeFiles/Makefile2:1436: recipe for target 'FAST_LIO_SLAM/SC-PGO/CMakeFiles/alaserPGO.dir/all' failed
make[1]: *** [FAST_LIO_SLAM/SC-PGO/CMakeFiles/alaserPGO.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
dji@dji-B85MG:~/catkin_fastlio_slam$

**Comment by kxch928925819** [comment]
# terminal 1: run FAST-LIO2 
    mkdir -p ~/catkin_fastlio_slam/src
    cd ~/catkin_fastlio_slam/src
    git clone https://github.com/gisbi-kim/FAST_LIO_SLAM.git
    git clone https://github.com/Livox-SDK/livox_ros_driver
    cd  /FAST_LIO_SLAM/FAST-LIO/
    git submodule update --init
    cd .. /..
    cd ..
    catkin_make
    source devel/setup.bash
    roslaunch fast_lio mapping_horizon.launch 

    # open the other terminal tab: run SC-PGO
    cd ~/catkin_fastlio_slam
    source devel/setup.bash
    roslaunch aloam_velodyne fastlio_ouster64.launch 

    # open the other terminal tab
    # rosbag play youfile.bag

**Comment by kxch928925819** [comment]
```
![Screenshot from 2021-07-27 19-34-42](https://user-images.githubusercontent.com/81554580/127148542-6e36f437-02a9-44be-9d9a-2a11d99b4176.png)
![Screenshot from 2021-07-27 19-35-49](https://user-images.githubusercontent.com/81554580/127148551-aa558a29-187e-4e56-8404-221dc02565a2.png)
![Screenshot from 2021-07-27 19-36-45](https://user-images.githubusercontent.com/81554580/127148558-4c92ceb3-9cd2-470b-ae09-f8f3cd54d9fa.png)
`
