### ISSUE TITLE
SC-PGO 在 livox horizon上运行失败

### ISSUE THREAD

**Issue by Lenotary** [gisbi-kim/FAST_LIO_SLAM#4]
使用如下参数，运行时候，SC-PGO 输出的 laser_odom_path 数据是错误的。好奇 为什么不直接使用 fast_lio 输出的 里程计数据
    <param name="scan_line" type="int" value="64" />

    
    <param name="mapping_skip_frame" type="int" value="1" />

    
    <param name="minimum_range" type="double" value="0.5"/>

    <param name="mapping_line_resolution" type="double" value="0.4"/> 
    <param name="mapping_plane_resolution" type="double" value="0.8"/> 

    
    <param name="keyframe_meter_gap" type="double" value="0.5"/>

    
    <param name="sc_dist_thres" type="double" value="0.2"/> 
    
    <param name="sc_max_radius" type="double" value="80.0"/> 

    
    <param name="lidar_type" type="string" value="OS1-64"/>
    <remap from="/velodyne_points" to="/cloud_registered"/>

    
    <param name="save_directory" type="string" value="/home/lenotary/work/file/data/"/>  

    
    <node pkg="aloam_velodyne" type="ascanRegistration" name="ascanRegistration" output="screen" /> 
    <node pkg="aloam_velodyne" type="alaserOdometry" name="alaserOdometry" output="screen" /> 
    <node pkg="aloam_velodyne" type="alaserMapping" name="alaserMapping" output="screen" /> 
    <node pkg="aloam_velodyne" type="alaserPGO" name="alaserPGO" output="screen" /> 

    
    <arg name="rviz" default="true" />
    <group if="$(arg rviz)">
        <node launch-prefix="nice" pkg="rviz" type="rviz" name="rviz_close" args="-d $(find aloam_velodyne)/rviz_cfg/aloam_velodyne.rviz" />
    </group>

**Comment by kxch928925819** [comment]
SC-PGO rviz /cloud_registered ！
terminal 1#
roslaunch fast_lio mapping_horizon.launch
terminal 2#
roslaunch aloam_velodyne fastlio_ouster64.launch 
terminal 3#
rosbag play  **_youfile_**.bag

**Comment by gisbi-kim** [comment]
hi, @Lenotary 
as @kxch928925819 commented, please use fastlio_ouster64.launch 

BTW,
for the livox-lidar's parameter set-ups, this repository still has slots that need to be improved.
I'll test and update the README in near future regarding the livox lidars.
