### ISSUE TITLE
question about function loopFindNearKeyframesCloud and variable _loop_kf_idx

### ISSUE THREAD

**Issue by ZeyingXuHuaWei** [gisbi-kim/FAST_LIO_SLAM#5]
Hello,  the second variable of function 
void loopFindNearKeyframesCloud( pcl::PointCloud<PointType>::Ptr& nearKeyframes, const int& key, const int& submap_size, const int& root_idx) in LaserPosegraphOptimization.cpp  is not used.

Another question:  why you use _loop_kf_idx but not _curr_kf_idx in the doICPVirtualRelative function？
![image](https://user-images.githubusercontent.com/63501237/126664658-5189e431-990a-45f4-bc28-d490f6816172.png)

**Comment by gisbi-kim** [comment]
hi, @ZeyingXuHuaWei  
I think this issue would be the answer. 
https://github.com/irapkaist/SC-LeGO-LOAM/issues/16

**Comment by QiMingZhenFan** [comment]
> hi, @ZeyingXuHuaWei
> I think this issue would be the answer.
> [irapkaist/SC-LeGO-LOAM#16](https://github.com/irapkaist/SC-LeGO-LOAM/issues/16)

hi, thanks for your reply. I have the same question as @ZeyingXuHuaWei does, and I followed the link you mentioned above.  But in my opinion, this situation is different from what is in your link. 
In the code mentioned by @ZeyingXuHuaWei, you use ICP to calculate the transform between **the target keyframe** (**old keyframe** where loop closure was found between the current keyframe and it) and the submap surrounding the target keyframe. Should there be a transform between **current keyframe** and the submap surrounding the target keyframe?
