### ISSUE TITLE
Ideal IMU Frequency and Time Synchronization

### ISSUE THREAD

**Issue by h-rover** [gisbi-kim/FAST_LIO_SLAM#6]
Hi,

Can you please suggest the ideal IMU frequency for this package? Plus, can you please comment on achieving better time synchronization between the IMU and Livox (Mid-70) Custom Messages ? 

Thanks.

**Comment by gisbi-kim** [comment]
hi @h-rover, first thank you for using our project. 
in the test videos in the README, I used the internal IMU in Ouster LiDAR. 

but for the livox-lidar's imu sync, please see the original fast-lio repository' issues.
