### ISSUE TITLE
<launch> Parameter

### ISSUE THREAD

**Issue by kxch928925819** [gisbi-kim/FAST_LIO_SLAM#7]
Kim, I collect rosbag in my residential area and use it

FAST_ LIO_ Slam has processed the data. The results of Fast - Lio are basically not too big problems. On the contrary, after the PCD integration of sc-pgo, they become a group.

I hope you can write down the description of parameter setting for further testing!

_This community has both ground (outdoor) and underground (indoor). the rosbag is 17.9G,I can't uploadgoogle cloud !

<launch>
 <param name="scan_line" type="int" value="64" />
    
    
    
    <param name="minimum_range" type="double" value="0.5"/>
    <param name="mapping_line_resolution" type="double" value="0.4"/> 
    <param name="mapping_plane_resolution" type="double" value="0.8"/> 
    <param name="mapviz_filter_size" type="double" value="0.05"/>
    
    <param name="keyframe_meter_gap" type="double" value="0.3"/>
    
    <param name="sc_dist_thres" type="double" value="0.3"/> 
    
    <param name="sc_max_radius" type="double" value="80.0"/> 
    
    <param name="lidar_type" type="string" value="OS1-64"/>
    
    <remap from="/aft_mapped_to_init" to="/Odometry"/>
    <remap from="/velodyne_cloud_registered_local" to="/cloud_registered_body"/>
    <remap from="/cloud_for_scancontext" to="/cloud_registered_lidar"/>   
    
    <param name="save_directory" type="string" value="/home/dji/catkin_fastlio_slam/data/"/>  
    
    <node pkg="aloam_velodyne" type="alaserPGO" name="alaserPGO" output="screen" /> 
    
    <arg name="rvizscpgo" default="true" />
    <group if="$(arg rvizscpgo)">
        <node launch-prefix="nice" pkg="rviz" type="rviz" name="rvizscpgo" args="-d $(find aloam_velodyne)/rviz_cfg/aloam_velodyne.rviz" />
    </group>

**Comment by gisbi-kim** [comment]
Thank you for the suggestion.
I'll made the parameter descriptions more fruitful in near future.
