### ISSUE TITLE
About GPS

### ISSUE THREAD

**Issue by LeisureLei** [gisbi-kim/FAST_LIO_SLAM#9]
I noticed that the GPS was subscribed in file laserPosegraphOptimization.cpp. But I did't find out who advertise GPS messages. I also noticed that GPS was used in videos of examples. So where are GPS messages published?

**Comment by gisbi-kim** [comment]
@LeisureLei  the GPS factors was implemented to demonstrate the system's stable z-height adjustment for MulRan dataset (this dataset has gps)

for more the gps functionality, 
please see here
https://github.com/gisbi-kim/SC-A-LOAM#riverside-01-mulran-dataset

**Comment by LeisureLei** [comment]
> @LeisureLei the GPS factors was implemented to demonstrate the system's stable z-height adjustment for MulRan dataset (this dataset has gps)
> 
> for more the gps functionality,
> please see here
> https://github.com/gisbi-kim/SC-A-LOAM#riverside-01-mulran-dataset

Got it! You just use gps altitude differences. I thought you also used both latitude and longitude.
